steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/${_PROJECT_ID}/${_GCR_REPO_NAME}/${_IMAGE_NAME}:${_VERSION}'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/${_PROJECT_ID}/${_GCR_REPO_NAME}/${_IMAGE_NAME}:${_VERSION}'
################## Deploying Terraform Code #############################


  # Initialize Terraform (install providers and modules)
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd task-1/
        terraform init

  # Validate Terraform configuration
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd task-1/
        terraform validate

  # Plan Terraform changes
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd task-1/
        terraform plan -input=false -out=tfplan

  # # Apply Terraform changes
  # - name: 'hashicorp/terraform:latest'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
        # cd task-1/
  #       terraform apply -auto-approve


# Specify the Cloud Logging configuration
logsBucket: 'gs://cloud-test-task'
options:
  logging: GCS_ONLY
