steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/${_PROJECT_ID}/${_GCR_REPO_NAME}/${_IMAGE_NAME}:${_VERSION}'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/${_PROJECT_ID}/${_GCR_REPO_NAME}/${_IMAGE_NAME}:${_VERSION}'

# Specify the Cloud Logging configuration
logsBucket: 'gs://cloud-test-task'
options:
  logging: GCS_ONLY
